services:
  frontend:
    build:
      context: ./greenX-assessment-tool-frontend
      dockerfile: Dockerfile      
    image: ghcr.io/zaheerabbas0/greenx-frontend
    container_name: Greenx_frontend
    ports:
      - "80:80"
    networks:
      - greenx-network

  backend:
    env_file:
    - .env
    build:
      context: ./GreenX_DCS_Assesment_Tool_Backend
      dockerfile: Dockerfile
    image: ghcr.io/zaheerabbas0/greenx-backend
    container_name: Greenx_backend
    ports:
      - "8000:8000"
    networks:
      - greenx-network
    depends_on:
      - greenx-db

  greenx-db:
    image: mysql:8.0
    container_name: greenx-db
    command: --ssl=0
    environment:
      MYSQL_ROOT_PASSWORD: inovaqo123
      MYSQL_DATABASE: all_tables
      MYSQL_USER: greenx_user
      MYSQL_PASSWORD: greenx_pass
    ports:
      - "3306:3306"
    networks:
      - greenx-network


networks:
  greenx-network:
    driver: bridge

