FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine

# default config hatao
RUN rm /etc/nginx/conf.d/default.conf

# apni config copy karo
COPY nginx.conf /etc/nginx/conf.d/default.conf

# React build copy karo
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
