name: CI/CD → ECS (OIDC)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: self-hosted
    environment: devops-plan

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
    # ---------------- CI ----------------
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: |
         echo "${{ secrets.GHCR_TOKEN }}" | \
         docker login ghcr.io -u zaheerabbas0 --password-stdin

    - name: Build Docker images
      run: docker compose build

    - name: Pull mysql image
      run: docker pull mysql:8.0

    - name: Tag images
      run: |
        docker tag ghcr.io/zaheerabbas0/greenx-frontend:latest ghcr.io/zaheerabbas0/greenx-frontend:${IMAGE_TAG}
        docker tag ghcr.io/zaheerabbas0/greenx-backend:latest  ghcr.io/zaheerabbas0/greenx-backend:${IMAGE_TAG}
        docker tag mysql:8.0 ghcr.io/zaheerabbas0/greenx-mysql:${IMAGE_TAG}

    - name: Push images
      run: |
        docker push ghcr.io/zaheerabbas0/greenx-frontend:latest
        docker push ghcr.io/zaheerabbas0/greenx-backend:latest

        # push commit SHA tags
        docker push ghcr.io/zaheerabbas0/greenx-frontend:${IMAGE_TAG}
        docker push ghcr.io/zaheerabbas0/greenx-backend:${IMAGE_TAG}
        docker push ghcr.io/zaheerabbas0/greenx-frontend:${IMAGE_TAG}
        docker push ghcr.io/zaheerabbas0/greenx-backend:${IMAGE_TAG}
        docker push ghcr.io/zaheerabbas0/greenx-mysql:${IMAGE_TAG}

   # ---------------- CD ----------------
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to ECS (frontend + backend + mysql)
      uses: donaldpiret/ecs-deploy@v0.2.0
      with:
        cluster: test-ecs-cluster-new
        target: test-task-definition-service
        tag: ${{ github.sha }}
        rollback: true
        timeout: 1000